//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVE.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.LoadTicket", CallbackContract=typeof(AVE.ServiceReference1.LoadTicketCallback))]
    public interface LoadTicket {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoadTicketCallback {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación SolicitaRedencion no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SolicitaRedencion(AVE.ServiceReference1.SolicitaRedencionResponse1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ConfirmacionCambioTarjeta no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ConfirmacionCambioTarjeta(AVE.ServiceReference1.ConfirmacionCambioTarjetaResponse1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ActualizaSocio no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ActualizaSocio(AVE.ServiceReference1.ActualizaSocioResponse1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ConsultaBeneficios no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ConsultaBeneficios(AVE.ServiceReference1.ConsultaBeneficiosResponse1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación SolicitudCambioTarjeta no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SolicitudCambioTarjeta(AVE.ServiceReference1.SolicitudCambioTarjetaResponse1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación EnviaTicket no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void EnviaTicket(AVE.ServiceReference1.EnviaTicketResponse1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación AltaSocio no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void AltaSocio(AVE.ServiceReference1.AltaSocioResponse1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ConfirmaOperacion no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ConfirmaOperacion(AVE.ServiceReference1.ConfirmaOperacionResponse1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación Checkpending no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Checkpending(AVE.ServiceReference1.CheckpendingResponse1 request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class SolicitaRedencionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string solicitaRedencionResultField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SolicitaRedencionResult {
            get {
                return this.solicitaRedencionResultField;
            }
            set {
                this.solicitaRedencionResultField = value;
                this.RaisePropertyChanged("SolicitaRedencionResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolicitaRedencionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AVE.ServiceReference1.SolicitaRedencionResponse SolicitaRedencionResponse;
        
        public SolicitaRedencionResponse1() {
        }
        
        public SolicitaRedencionResponse1(AVE.ServiceReference1.SolicitaRedencionResponse SolicitaRedencionResponse) {
            this.SolicitaRedencionResponse = SolicitaRedencionResponse;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class ConfirmacionCambioTarjetaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string confirmacionCambioTarjetaResultField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ConfirmacionCambioTarjetaResult {
            get {
                return this.confirmacionCambioTarjetaResultField;
            }
            set {
                this.confirmacionCambioTarjetaResultField = value;
                this.RaisePropertyChanged("ConfirmacionCambioTarjetaResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmacionCambioTarjetaResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AVE.ServiceReference1.ConfirmacionCambioTarjetaResponse ConfirmacionCambioTarjetaResponse;
        
        public ConfirmacionCambioTarjetaResponse1() {
        }
        
        public ConfirmacionCambioTarjetaResponse1(AVE.ServiceReference1.ConfirmacionCambioTarjetaResponse ConfirmacionCambioTarjetaResponse) {
            this.ConfirmacionCambioTarjetaResponse = ConfirmacionCambioTarjetaResponse;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class ActualizaSocioResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string actualizaSocioResultField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ActualizaSocioResult {
            get {
                return this.actualizaSocioResultField;
            }
            set {
                this.actualizaSocioResultField = value;
                this.RaisePropertyChanged("ActualizaSocioResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizaSocioResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AVE.ServiceReference1.ActualizaSocioResponse ActualizaSocioResponse;
        
        public ActualizaSocioResponse1() {
        }
        
        public ActualizaSocioResponse1(AVE.ServiceReference1.ActualizaSocioResponse ActualizaSocioResponse) {
            this.ActualizaSocioResponse = ActualizaSocioResponse;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class ConsultaBeneficiosResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string consultaBeneficiosResultField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ConsultaBeneficiosResult {
            get {
                return this.consultaBeneficiosResultField;
            }
            set {
                this.consultaBeneficiosResultField = value;
                this.RaisePropertyChanged("ConsultaBeneficiosResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaBeneficiosResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AVE.ServiceReference1.ConsultaBeneficiosResponse ConsultaBeneficiosResponse;
        
        public ConsultaBeneficiosResponse1() {
        }
        
        public ConsultaBeneficiosResponse1(AVE.ServiceReference1.ConsultaBeneficiosResponse ConsultaBeneficiosResponse) {
            this.ConsultaBeneficiosResponse = ConsultaBeneficiosResponse;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class SolicitudCambioTarjetaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string solicitudCambioTarjetaResultField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SolicitudCambioTarjetaResult {
            get {
                return this.solicitudCambioTarjetaResultField;
            }
            set {
                this.solicitudCambioTarjetaResultField = value;
                this.RaisePropertyChanged("SolicitudCambioTarjetaResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolicitudCambioTarjetaResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AVE.ServiceReference1.SolicitudCambioTarjetaResponse SolicitudCambioTarjetaResponse;
        
        public SolicitudCambioTarjetaResponse1() {
        }
        
        public SolicitudCambioTarjetaResponse1(AVE.ServiceReference1.SolicitudCambioTarjetaResponse SolicitudCambioTarjetaResponse) {
            this.SolicitudCambioTarjetaResponse = SolicitudCambioTarjetaResponse;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class EnviaTicketResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string enviaTicketResultField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EnviaTicketResult {
            get {
                return this.enviaTicketResultField;
            }
            set {
                this.enviaTicketResultField = value;
                this.RaisePropertyChanged("EnviaTicketResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaTicketResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AVE.ServiceReference1.EnviaTicketResponse EnviaTicketResponse;
        
        public EnviaTicketResponse1() {
        }
        
        public EnviaTicketResponse1(AVE.ServiceReference1.EnviaTicketResponse EnviaTicketResponse) {
            this.EnviaTicketResponse = EnviaTicketResponse;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class AltaSocioResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string altaSocioResultField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AltaSocioResult {
            get {
                return this.altaSocioResultField;
            }
            set {
                this.altaSocioResultField = value;
                this.RaisePropertyChanged("AltaSocioResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltaSocioResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AVE.ServiceReference1.AltaSocioResponse AltaSocioResponse;
        
        public AltaSocioResponse1() {
        }
        
        public AltaSocioResponse1(AVE.ServiceReference1.AltaSocioResponse AltaSocioResponse) {
            this.AltaSocioResponse = AltaSocioResponse;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class ConfirmaOperacionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string confirmaOperacionResultField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ConfirmaOperacionResult {
            get {
                return this.confirmaOperacionResultField;
            }
            set {
                this.confirmaOperacionResultField = value;
                this.RaisePropertyChanged("ConfirmaOperacionResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmaOperacionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AVE.ServiceReference1.ConfirmaOperacionResponse ConfirmaOperacionResponse;
        
        public ConfirmaOperacionResponse1() {
        }
        
        public ConfirmaOperacionResponse1(AVE.ServiceReference1.ConfirmaOperacionResponse ConfirmaOperacionResponse) {
            this.ConfirmaOperacionResponse = ConfirmaOperacionResponse;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class CheckpendingResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string checkpendingResultField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CheckpendingResult {
            get {
                return this.checkpendingResultField;
            }
            set {
                this.checkpendingResultField = value;
                this.RaisePropertyChanged("CheckpendingResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckpendingResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AVE.ServiceReference1.CheckpendingResponse CheckpendingResponse;
        
        public CheckpendingResponse1() {
        }
        
        public CheckpendingResponse1(AVE.ServiceReference1.CheckpendingResponse CheckpendingResponse) {
            this.CheckpendingResponse = CheckpendingResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoadTicketChannel : AVE.ServiceReference1.LoadTicket, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoadTicketClient : System.ServiceModel.DuplexClientBase<AVE.ServiceReference1.LoadTicket>, AVE.ServiceReference1.LoadTicket {
        
        public LoadTicketClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public LoadTicketClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public LoadTicketClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LoadTicketClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LoadTicketClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
    }
}
