//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLLGestionCliente9.ServicioModdoOnline {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ModdoGroup.org/WsOnline/", ConfigurationName="ServicioModdoOnline.SModdoOnlineSoap")]
    public interface SModdoOnlineSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/SetUpVentas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short SetUpVentas(System.Data.DataSet DsVentas, string DirFTP, System.DateTime FechaSesion, string StrTienda, string strIdKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/DownTicketBackUp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short DownTicketBackUp(ref System.Data.DataSet DsTicket, string DirFTP, System.DateTime FechaSesion, string StrTienda, string strIDKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/DownTicketDevolucion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short DownTicketDevolucion(ref System.Data.DataSet DsTicket, string DirFTP, System.DateTime FechaSesion, string StrTienda, string strIDKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/InsertVale", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertVale(string DatosVale, string FechaSesion, string DirFTP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/UpdateStockTienda", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short UpdateStockTienda(DLLGestionCliente9.ServicioModdoOnline.Articulo[] LstArticulo, ref System.Data.DataSet DsStock, ref System.DateTime FechaSesion, string DirFTP, string StrTienda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/SetupCargos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short SetupCargos(ref System.Data.DataSet DsCargos, string DirFTP, System.DateTime FechaSesion, string StrTienda, string strIdKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/DownCargoTienda", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short DownCargoTienda(ref System.Data.DataSet DsCargo, string DirFTP, System.DateTime FechaSesion, string StrTienda, string strIDKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/DownHistorico", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short DownHistorico(ref System.Data.DataSet DsHistorico, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey, ref System.DateTime FechaInicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/UpdateVales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short UpdateVales(ref System.Data.DataSet dsVales, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/DownVales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short DownVales(ref System.Data.DataSet DsVales, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/UpEntradaPedidos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short UpEntradaPedidos(ref System.Data.DataSet dsEntradaPedidos, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/UpEntradaCargo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short UpEntradaCargo(ref System.Data.DataSet dsEntradaCargos, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/DameVersionWS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DameVersionWS(string versionTPVOnline, ref string VersionWSOnline, string UriWS, string Tienda, string DirFTP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/DownViajeros", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short DownViajeros(System.Data.DataSet tbCargo, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey, ref System.Data.DataSet dtSalida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/UpActualizarViajeros_DownCargosEmitidosAuto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short UpActualizarViajeros_DownCargosEmitidosAuto(System.Data.DataSet tbCargo, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey, ref System.Data.DataSet dtSalida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/UpSolicitudReparto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short UpSolicitudReparto(ref System.Data.DataSet dsSolicitudReparto, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/GetRepartosPtes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short GetRepartosPtes(string DirFTP, System.DateTime FechaSesion, ref System.Data.DataSet DsSolicitudReparto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/DownSolicitudRepartoPteAUTO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short DownSolicitudRepartoPteAUTO(string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey, ref System.Data.DataSet DsSolicitudReparto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/DownSolicitudRepartoAUTO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short DownSolicitudRepartoAUTO(System.Data.DataSet dsSolRepartoIn, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey, ref System.Data.DataSet DsSolicitudReparto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/UpdateStockTiendaPaginacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short UpdateStockTiendaPaginacion(DLLGestionCliente9.ServicioModdoOnline.Articulo[] LstArticulo, ref System.Data.DataSet DsStock, ref System.DateTime FechaSesion, string DirFTP, string StrTienda, ref long NumTotal, long IniPagina, long FinPagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/DownPedidos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short DownPedidos(ref System.Data.DataSet dsPedidos, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey, short ExisteLocal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/SetUpDownClientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short SetUpDownClientes(ref System.Data.DataSet DsClientes, string DirFTP, System.DateTime FechaSesion, string StrTienda, string strIdKey, short TipoOperacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/SendCorreo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short SendCorreo(ref System.Data.DataSet dsCorreo, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/DownCorreoLeido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short DownCorreoLeido(System.Data.DataSet dsCorreos, string DirFTP, System.DateTime FechaSesion, string StrTienda, ref System.Data.DataSet dsOut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/SendCorreoLeido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short SendCorreoLeido(string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/DownCorreoAUTO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short DownCorreoAUTO(System.Data.DataSet dsCorreoIn, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey, ref System.Data.DataSet DsCorreoOut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/CambioSesion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CambioSesion(string DirFTP, string fecha_Old, string fecha_New, string IdTienda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/InsertPedido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] InsertPedido(string DirFTP, string idSeguimiento, string numeroPedidoSAP, string numeroEntregaSAP, string codigoAlfa, string talla, string tienda, short cantidad, string numeroPedimento, string Aduana, System.DateTime fechaPedimento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/CancelaReserva", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CancelaReserva(string xmlHermes, string IdTiendaCancelacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/CheckDatosTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CheckDatosTicket(long numTicket, ref System.Data.DataSet ds, string DirFTP, string IdTienda, System.DateTime FechaSesion, string IdTerminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/CheckDatosClientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CheckDatosClientes(ref System.Data.DataSet ds, string DirFTP, string IdTienda, System.DateTime FechaSesion, string IdTerminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/DownEntradaPedidoTienda", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DownEntradaPedidoTienda(ref System.Data.DataSet ds, string DirFTP, System.DateTime FechaSesion, string Tienda, long IdEntradaPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/DownEntradaCargoTienda", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DownEntradaCargoTienda(ref System.Data.DataSet ds, string DirFTP, System.DateTime FechaSesion, string Tienda, long IdCargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/CheckDatosEntradaPedidos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CheckDatosEntradaPedidos(string numPedidos, ref System.Data.DataSet ds, string DirFTP, string IdTienda, System.DateTime FechaSesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/CheckDatosEntradaCargos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CheckDatosEntradaCargos(string numCargos, ref System.Data.DataSet ds, string DirFTP, string IdTienda, System.DateTime FechaSesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/CheckDatosCargos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CheckDatosCargos(string numCargos, ref System.Data.DataSet ds, string DirFTP, string IdTienda, System.DateTime FechaSesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/CheckVersionTPVOnline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckVersionTPVOnline(string Cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/CheckVersionCentral", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckVersionCentral(string Cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/DownPreciosNulos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short DownPreciosNulos(System.Data.DataSet DsPrecios, ref System.Data.DataSet DsPrecioOut, System.DateTime FechaSesion, string DirFTP, string StrTienda, int Paginacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/Get_Entidades_GENERIC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short Get_Entidades_GENERIC(ref System.Data.DataSet DsGeneric, string StrKey, DLLGestionCliente9.ServicioModdoOnline.Entidades Entidad, System.DateTime FechaSesion, string DirFTP, string StrTienda, long InicioPag, long FINPag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/PushPopUpSolicitudPedido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PushPopUpSolicitudPedido(string xmlSolicitudPedido, string UserPassWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/DownSolicitudPresta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        short DownSolicitudPresta(ref System.Data.DataSet DsSolicitud, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/PedidoConfirmadoPresta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PedidoConfirmadoPresta(string xmlPedidoConfirmado, string UserPassWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/VentaConfirmadoPresta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string VentaConfirmadoPresta(string xmlVentaConfirmada, string UserPassWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModdoGroup.org/WsOnline/DevolucionConfirmadaPresta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DevolucionConfirmadaPresta(int idOrder, string Ean, string UserPassWord);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ModdoGroup.org/WsOnline/")]
    public partial class Articulo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idArticuloField;
        
        private string codigoAlfaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long IdArticulo {
            get {
                return this.idArticuloField;
            }
            set {
                this.idArticuloField = value;
                this.RaisePropertyChanged("IdArticulo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CodigoAlfa {
            get {
                return this.codigoAlfaField;
            }
            set {
                this.codigoAlfaField = value;
                this.RaisePropertyChanged("CodigoAlfa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ModdoGroup.org/WsOnline/")]
    public enum Entidades {
        
        /// <comentarios/>
        Tiendas,
        
        /// <comentarios/>
        Empleados,
        
        /// <comentarios/>
        KARDEX,
        
        /// <comentarios/>
        DESCARGAF7,
        
        /// <comentarios/>
        UPFACTURA,
        
        /// <comentarios/>
        REPARTOS,
        
        /// <comentarios/>
        GetNumCargo,
        
        /// <comentarios/>
        CargoTiendaSesion,
        
        /// <comentarios/>
        CARGOAUTAVE,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SModdoOnlineSoapChannel : DLLGestionCliente9.ServicioModdoOnline.SModdoOnlineSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SModdoOnlineSoapClient : System.ServiceModel.ClientBase<DLLGestionCliente9.ServicioModdoOnline.SModdoOnlineSoap>, DLLGestionCliente9.ServicioModdoOnline.SModdoOnlineSoap {
        
        public SModdoOnlineSoapClient() {
        }
        
        public SModdoOnlineSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SModdoOnlineSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SModdoOnlineSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SModdoOnlineSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public short SetUpVentas(System.Data.DataSet DsVentas, string DirFTP, System.DateTime FechaSesion, string StrTienda, string strIdKey) {
            return base.Channel.SetUpVentas(DsVentas, DirFTP, FechaSesion, StrTienda, strIdKey);
        }
        
        public short DownTicketBackUp(ref System.Data.DataSet DsTicket, string DirFTP, System.DateTime FechaSesion, string StrTienda, string strIDKey) {
            return base.Channel.DownTicketBackUp(ref DsTicket, DirFTP, FechaSesion, StrTienda, strIDKey);
        }
        
        public short DownTicketDevolucion(ref System.Data.DataSet DsTicket, string DirFTP, System.DateTime FechaSesion, string StrTienda, string strIDKey) {
            return base.Channel.DownTicketDevolucion(ref DsTicket, DirFTP, FechaSesion, StrTienda, strIDKey);
        }
        
        public string InsertVale(string DatosVale, string FechaSesion, string DirFTP) {
            return base.Channel.InsertVale(DatosVale, FechaSesion, DirFTP);
        }
        
        public short UpdateStockTienda(DLLGestionCliente9.ServicioModdoOnline.Articulo[] LstArticulo, ref System.Data.DataSet DsStock, ref System.DateTime FechaSesion, string DirFTP, string StrTienda) {
            return base.Channel.UpdateStockTienda(LstArticulo, ref DsStock, ref FechaSesion, DirFTP, StrTienda);
        }
        
        public short SetupCargos(ref System.Data.DataSet DsCargos, string DirFTP, System.DateTime FechaSesion, string StrTienda, string strIdKey) {
            return base.Channel.SetupCargos(ref DsCargos, DirFTP, FechaSesion, StrTienda, strIdKey);
        }
        
        public short DownCargoTienda(ref System.Data.DataSet DsCargo, string DirFTP, System.DateTime FechaSesion, string StrTienda, string strIDKey) {
            return base.Channel.DownCargoTienda(ref DsCargo, DirFTP, FechaSesion, StrTienda, strIDKey);
        }
        
        public short DownHistorico(ref System.Data.DataSet DsHistorico, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey, ref System.DateTime FechaInicio) {
            return base.Channel.DownHistorico(ref DsHistorico, DirFTP, FechaSesion, StrTienda, StrIDKey, ref FechaInicio);
        }
        
        public short UpdateVales(ref System.Data.DataSet dsVales, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey) {
            return base.Channel.UpdateVales(ref dsVales, DirFTP, FechaSesion, StrTienda, StrIDKey);
        }
        
        public short DownVales(ref System.Data.DataSet DsVales, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey) {
            return base.Channel.DownVales(ref DsVales, DirFTP, FechaSesion, StrTienda, StrIDKey);
        }
        
        public short UpEntradaPedidos(ref System.Data.DataSet dsEntradaPedidos, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey) {
            return base.Channel.UpEntradaPedidos(ref dsEntradaPedidos, DirFTP, FechaSesion, StrTienda, StrIDKey);
        }
        
        public short UpEntradaCargo(ref System.Data.DataSet dsEntradaCargos, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey) {
            return base.Channel.UpEntradaCargo(ref dsEntradaCargos, DirFTP, FechaSesion, StrTienda, StrIDKey);
        }
        
        public int DameVersionWS(string versionTPVOnline, ref string VersionWSOnline, string UriWS, string Tienda, string DirFTP) {
            return base.Channel.DameVersionWS(versionTPVOnline, ref VersionWSOnline, UriWS, Tienda, DirFTP);
        }
        
        public short DownViajeros(System.Data.DataSet tbCargo, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey, ref System.Data.DataSet dtSalida) {
            return base.Channel.DownViajeros(tbCargo, DirFTP, FechaSesion, StrTienda, StrIDKey, ref dtSalida);
        }
        
        public short UpActualizarViajeros_DownCargosEmitidosAuto(System.Data.DataSet tbCargo, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey, ref System.Data.DataSet dtSalida) {
            return base.Channel.UpActualizarViajeros_DownCargosEmitidosAuto(tbCargo, DirFTP, FechaSesion, StrTienda, StrIDKey, ref dtSalida);
        }
        
        public short UpSolicitudReparto(ref System.Data.DataSet dsSolicitudReparto, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey) {
            return base.Channel.UpSolicitudReparto(ref dsSolicitudReparto, DirFTP, FechaSesion, StrTienda, StrIDKey);
        }
        
        public short GetRepartosPtes(string DirFTP, System.DateTime FechaSesion, ref System.Data.DataSet DsSolicitudReparto) {
            return base.Channel.GetRepartosPtes(DirFTP, FechaSesion, ref DsSolicitudReparto);
        }
        
        public short DownSolicitudRepartoPteAUTO(string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey, ref System.Data.DataSet DsSolicitudReparto) {
            return base.Channel.DownSolicitudRepartoPteAUTO(DirFTP, FechaSesion, StrTienda, StrIDKey, ref DsSolicitudReparto);
        }
        
        public short DownSolicitudRepartoAUTO(System.Data.DataSet dsSolRepartoIn, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey, ref System.Data.DataSet DsSolicitudReparto) {
            return base.Channel.DownSolicitudRepartoAUTO(dsSolRepartoIn, DirFTP, FechaSesion, StrTienda, StrIDKey, ref DsSolicitudReparto);
        }
        
        public short UpdateStockTiendaPaginacion(DLLGestionCliente9.ServicioModdoOnline.Articulo[] LstArticulo, ref System.Data.DataSet DsStock, ref System.DateTime FechaSesion, string DirFTP, string StrTienda, ref long NumTotal, long IniPagina, long FinPagina) {
            return base.Channel.UpdateStockTiendaPaginacion(LstArticulo, ref DsStock, ref FechaSesion, DirFTP, StrTienda, ref NumTotal, IniPagina, FinPagina);
        }
        
        public short DownPedidos(ref System.Data.DataSet dsPedidos, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey, short ExisteLocal) {
            return base.Channel.DownPedidos(ref dsPedidos, DirFTP, FechaSesion, StrTienda, StrIDKey, ExisteLocal);
        }
        
        public short SetUpDownClientes(ref System.Data.DataSet DsClientes, string DirFTP, System.DateTime FechaSesion, string StrTienda, string strIdKey, short TipoOperacion) {
            return base.Channel.SetUpDownClientes(ref DsClientes, DirFTP, FechaSesion, StrTienda, strIdKey, TipoOperacion);
        }
        
        public short SendCorreo(ref System.Data.DataSet dsCorreo, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey) {
            return base.Channel.SendCorreo(ref dsCorreo, DirFTP, FechaSesion, StrTienda, StrIDKey);
        }
        
        public short DownCorreoLeido(System.Data.DataSet dsCorreos, string DirFTP, System.DateTime FechaSesion, string StrTienda, ref System.Data.DataSet dsOut) {
            return base.Channel.DownCorreoLeido(dsCorreos, DirFTP, FechaSesion, StrTienda, ref dsOut);
        }
        
        public short SendCorreoLeido(string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey) {
            return base.Channel.SendCorreoLeido(DirFTP, FechaSesion, StrTienda, StrIDKey);
        }
        
        public short DownCorreoAUTO(System.Data.DataSet dsCorreoIn, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey, ref System.Data.DataSet DsCorreoOut) {
            return base.Channel.DownCorreoAUTO(dsCorreoIn, DirFTP, FechaSesion, StrTienda, StrIDKey, ref DsCorreoOut);
        }
        
        public int CambioSesion(string DirFTP, string fecha_Old, string fecha_New, string IdTienda) {
            return base.Channel.CambioSesion(DirFTP, fecha_Old, fecha_New, IdTienda);
        }
        
        public string[] InsertPedido(string DirFTP, string idSeguimiento, string numeroPedidoSAP, string numeroEntregaSAP, string codigoAlfa, string talla, string tienda, short cantidad, string numeroPedimento, string Aduana, System.DateTime fechaPedimento) {
            return base.Channel.InsertPedido(DirFTP, idSeguimiento, numeroPedidoSAP, numeroEntregaSAP, codigoAlfa, talla, tienda, cantidad, numeroPedimento, Aduana, fechaPedimento);
        }
        
        public string CancelaReserva(string xmlHermes, string IdTiendaCancelacion) {
            return base.Channel.CancelaReserva(xmlHermes, IdTiendaCancelacion);
        }
        
        public int CheckDatosTicket(long numTicket, ref System.Data.DataSet ds, string DirFTP, string IdTienda, System.DateTime FechaSesion, string IdTerminal) {
            return base.Channel.CheckDatosTicket(numTicket, ref ds, DirFTP, IdTienda, FechaSesion, IdTerminal);
        }
        
        public int CheckDatosClientes(ref System.Data.DataSet ds, string DirFTP, string IdTienda, System.DateTime FechaSesion, string IdTerminal) {
            return base.Channel.CheckDatosClientes(ref ds, DirFTP, IdTienda, FechaSesion, IdTerminal);
        }
        
        public int DownEntradaPedidoTienda(ref System.Data.DataSet ds, string DirFTP, System.DateTime FechaSesion, string Tienda, long IdEntradaPedido) {
            return base.Channel.DownEntradaPedidoTienda(ref ds, DirFTP, FechaSesion, Tienda, IdEntradaPedido);
        }
        
        public int DownEntradaCargoTienda(ref System.Data.DataSet ds, string DirFTP, System.DateTime FechaSesion, string Tienda, long IdCargo) {
            return base.Channel.DownEntradaCargoTienda(ref ds, DirFTP, FechaSesion, Tienda, IdCargo);
        }
        
        public int CheckDatosEntradaPedidos(string numPedidos, ref System.Data.DataSet ds, string DirFTP, string IdTienda, System.DateTime FechaSesion) {
            return base.Channel.CheckDatosEntradaPedidos(numPedidos, ref ds, DirFTP, IdTienda, FechaSesion);
        }
        
        public int CheckDatosEntradaCargos(string numCargos, ref System.Data.DataSet ds, string DirFTP, string IdTienda, System.DateTime FechaSesion) {
            return base.Channel.CheckDatosEntradaCargos(numCargos, ref ds, DirFTP, IdTienda, FechaSesion);
        }
        
        public int CheckDatosCargos(string numCargos, ref System.Data.DataSet ds, string DirFTP, string IdTienda, System.DateTime FechaSesion) {
            return base.Channel.CheckDatosCargos(numCargos, ref ds, DirFTP, IdTienda, FechaSesion);
        }
        
        public string CheckVersionTPVOnline(string Cliente) {
            return base.Channel.CheckVersionTPVOnline(Cliente);
        }
        
        public string CheckVersionCentral(string Cliente) {
            return base.Channel.CheckVersionCentral(Cliente);
        }
        
        public short DownPreciosNulos(System.Data.DataSet DsPrecios, ref System.Data.DataSet DsPrecioOut, System.DateTime FechaSesion, string DirFTP, string StrTienda, int Paginacion) {
            return base.Channel.DownPreciosNulos(DsPrecios, ref DsPrecioOut, FechaSesion, DirFTP, StrTienda, Paginacion);
        }
        
        public short Get_Entidades_GENERIC(ref System.Data.DataSet DsGeneric, string StrKey, DLLGestionCliente9.ServicioModdoOnline.Entidades Entidad, System.DateTime FechaSesion, string DirFTP, string StrTienda, long InicioPag, long FINPag) {
            return base.Channel.Get_Entidades_GENERIC(ref DsGeneric, StrKey, Entidad, FechaSesion, DirFTP, StrTienda, InicioPag, FINPag);
        }
        
        public string PushPopUpSolicitudPedido(string xmlSolicitudPedido, string UserPassWord) {
            return base.Channel.PushPopUpSolicitudPedido(xmlSolicitudPedido, UserPassWord);
        }
        
        public short DownSolicitudPresta(ref System.Data.DataSet DsSolicitud, string DirFTP, System.DateTime FechaSesion, string StrTienda, string StrIDKey) {
            return base.Channel.DownSolicitudPresta(ref DsSolicitud, DirFTP, FechaSesion, StrTienda, StrIDKey);
        }
        
        public string PedidoConfirmadoPresta(string xmlPedidoConfirmado, string UserPassWord) {
            return base.Channel.PedidoConfirmadoPresta(xmlPedidoConfirmado, UserPassWord);
        }
        
        public string VentaConfirmadoPresta(string xmlVentaConfirmada, string UserPassWord) {
            return base.Channel.VentaConfirmadoPresta(xmlVentaConfirmada, UserPassWord);
        }
        
        public bool DevolucionConfirmadaPresta(int idOrder, string Ean, string UserPassWord) {
            return base.Channel.DevolucionConfirmadaPresta(idOrder, Ean, UserPassWord);
        }
    }
}
