//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34014.
// 
#pragma warning disable 1591

namespace DLLGestionVenta.AlmacenCentralPiaguiServiceReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsAlmacenCentralSoap", Namespace="http://mypiagui.com:9090/")]
    public partial class wsAlmacenCentral : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback setSapConexionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInventarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback creaPedidoACOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsAlmacenCentral() {
            this.Url = global::DLLGestionVenta.Properties.Settings.Default.DLLGestionVenta_AlmacenCentralPiaguiServiceReference_wsAlmacenCentral;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event setSapConexionCompletedEventHandler setSapConexionCompleted;
        
        /// <remarks/>
        public event getInventarioCompletedEventHandler getInventarioCompleted;
        
        /// <remarks/>
        public event creaPedidoACCompletedEventHandler creaPedidoACCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mypiagui.com:9090/Login", RequestNamespace="http://mypiagui.com:9090/", ResponseNamespace="http://mypiagui.com:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Login(string User, string Pwd) {
            object[] results = this.Invoke("Login", new object[] {
                        User,
                        Pwd});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string User, string Pwd) {
            this.LoginAsync(User, Pwd, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string User, string Pwd, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        User,
                        Pwd}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mypiagui.com:9090/setSapConexion", RequestNamespace="http://mypiagui.com:9090/", ResponseNamespace="http://mypiagui.com:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object setSapConexion() {
            object[] results = this.Invoke("setSapConexion", new object[0]);
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void setSapConexionAsync() {
            this.setSapConexionAsync(null);
        }
        
        /// <remarks/>
        public void setSapConexionAsync(object userState) {
            if ((this.setSapConexionOperationCompleted == null)) {
                this.setSapConexionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetSapConexionOperationCompleted);
            }
            this.InvokeAsync("setSapConexion", new object[0], this.setSapConexionOperationCompleted, userState);
        }
        
        private void OnsetSapConexionOperationCompleted(object arg) {
            if ((this.setSapConexionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setSapConexionCompleted(this, new setSapConexionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mypiagui.com:9090/getInventario", RequestNamespace="http://mypiagui.com:9090/", ResponseNamespace="http://mypiagui.com:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode getInventario(string Material) {
            object[] results = this.Invoke("getInventario", new object[] {
                        Material});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void getInventarioAsync(string Material) {
            this.getInventarioAsync(Material, null);
        }
        
        /// <remarks/>
        public void getInventarioAsync(string Material, object userState) {
            if ((this.getInventarioOperationCompleted == null)) {
                this.getInventarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInventarioOperationCompleted);
            }
            this.InvokeAsync("getInventario", new object[] {
                        Material}, this.getInventarioOperationCompleted, userState);
        }
        
        private void OngetInventarioOperationCompleted(object arg) {
            if ((this.getInventarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInventarioCompleted(this, new getInventarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mypiagui.com:9090/creaPedidoAC", RequestNamespace="http://mypiagui.com:9090/", ResponseNamespace="http://mypiagui.com:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode creaPedidoAC(string NoTraspaso, string Centro, string Almacen, string Tienda, string Material, string Talla, int Cantidad) {
            object[] results = this.Invoke("creaPedidoAC", new object[] {
                        NoTraspaso,
                        Centro,
                        Almacen,
                        Tienda,
                        Material,
                        Talla,
                        Cantidad});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void creaPedidoACAsync(string NoTraspaso, string Centro, string Almacen, string Tienda, string Material, string Talla, int Cantidad) {
            this.creaPedidoACAsync(NoTraspaso, Centro, Almacen, Tienda, Material, Talla, Cantidad, null);
        }
        
        /// <remarks/>
        public void creaPedidoACAsync(string NoTraspaso, string Centro, string Almacen, string Tienda, string Material, string Talla, int Cantidad, object userState) {
            if ((this.creaPedidoACOperationCompleted == null)) {
                this.creaPedidoACOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreaPedidoACOperationCompleted);
            }
            this.InvokeAsync("creaPedidoAC", new object[] {
                        NoTraspaso,
                        Centro,
                        Almacen,
                        Tienda,
                        Material,
                        Talla,
                        Cantidad}, this.creaPedidoACOperationCompleted, userState);
        }
        
        private void OncreaPedidoACOperationCompleted(object arg) {
            if ((this.creaPedidoACCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.creaPedidoACCompleted(this, new creaPedidoACCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void setSapConexionCompletedEventHandler(object sender, setSapConexionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setSapConexionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setSapConexionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getInventarioCompletedEventHandler(object sender, getInventarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInventarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInventarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void creaPedidoACCompletedEventHandler(object sender, creaPedidoACCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class creaPedidoACCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal creaPedidoACCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591