//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir.
        /// </summary>
        internal static string Abrir {
            get {
                return ResourceManager.GetString("Abrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        internal static string Apellidos {
            get {
                return ResourceManager.GetString("Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículo.
        /// </summary>
        internal static string Articulo {
            get {
                return ResourceManager.GetString("Articulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El artículo seleccionado está fuera del perímetro de la orden de inventario..
        /// </summary>
        internal static string ArticuloFueraPerimetro {
            get {
                return ResourceManager.GetString("ArticuloFueraPerimetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un articulo para realizar el guardado..
        /// </summary>
        internal static string ArticuloObligatorio {
            get {
                return ResourceManager.GetString("ArticuloObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículos totales.
        /// </summary>
        internal static string ArticulosTotales {
            get {
                return ResourceManager.GetString("ArticulosTotales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asesor de ventas.
        /// </summary>
        internal static string AsesorVentas {
            get {
                return ResourceManager.GetString("AsesorVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atrás.
        /// </summary>
        internal static string Atras {
            get {
                return ResourceManager.GetString("Atras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A pagar.
        /// </summary>
        internal static string A_pagar {
            get {
                return ResourceManager.GetString("A_pagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        internal static string Añadir {
            get {
                return ResourceManager.GetString("Añadir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un nombre de bloque..
        /// </summary>
        internal static string BloqueObligatorio {
            get {
                return ResourceManager.GetString("BloqueObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        internal static string Borrar {
            get {
                return ResourceManager.GetString("Borrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar cliente.
        /// </summary>
        internal static string BuscarCliente {
            get {
                return ResourceManager.GetString("BuscarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar pedido.
        /// </summary>
        internal static string BuscarPedido {
            get {
                return ResourceManager.GetString("BuscarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar estado a.
        /// </summary>
        internal static string CambiarEstado {
            get {
                return ResourceManager.GetString("CambiarEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel..
        /// </summary>
        internal static string CancelarAbrev {
            get {
                return ResourceManager.GetString("CancelarAbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir una cantidad válida..
        /// </summary>
        internal static string CantidadNoValida {
            get {
                return ResourceManager.GetString("CantidadNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad total de unidades.
        /// </summary>
        internal static string CantidadTotalUnidades {
            get {
                return ResourceManager.GetString("CantidadTotalUnidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargos.
        /// </summary>
        internal static string Cargos {
            get {
                return ResourceManager.GetString("Cargos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle del cargo.
        /// </summary>
        internal static string CargosDetalle {
            get {
                return ResourceManager.GetString("CargosDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entr. Carg..
        /// </summary>
        internal static string CargosEntrada {
            get {
                return ResourceManager.GetString("CargosEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargo  registrado con el nº.
        /// </summary>
        internal static string CargoSolicitudRegistrado {
            get {
                return ResourceManager.GetString("CargoSolicitudRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo.
        /// </summary>
        internal static string Catalogo {
            get {
                return ResourceManager.GetString("Catalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CIF.
        /// </summary>
        internal static string CIF {
            get {
                return ResourceManager.GetString("CIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        internal static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Alfa.
        /// </summary>
        internal static string CodigoAlfa {
            get {
                return ResourceManager.GetString("CodigoAlfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Postal.
        /// </summary>
        internal static string CodigoPostal {
            get {
                return ResourceManager.GetString("CodigoPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentario (Campo Abierto).
        /// </summary>
        internal static string Comentario {
            get {
                return ResourceManager.GetString("Comentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compl.
        /// </summary>
        internal static string Complementos {
            get {
                return ResourceManager.GetString("Complementos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea borrar el registro actual?.
        /// </summary>
        internal static string ConfirmarBorrar {
            get {
                return ResourceManager.GetString("ConfirmarBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea borrar la entrada?.
        /// </summary>
        internal static string ConfirmarBorrarEntrada {
            get {
                return ResourceManager.GetString("ConfirmarBorrarEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea cancelar? Los datos serán borrados..
        /// </summary>
        internal static string ConfirmarCancelar {
            get {
                return ResourceManager.GetString("ConfirmarCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea finalizar?.
        /// </summary>
        internal static string ConfirmarFinalizar {
            get {
                return ResourceManager.GetString("ConfirmarFinalizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea finalizar esta entrada?.
        /// </summary>
        internal static string ConfirmarFinalizarEntrada {
            get {
                return ResourceManager.GetString("ConfirmarFinalizarEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea salir?.
        /// </summary>
        internal static string ConfirmarSalir {
            get {
                return ResourceManager.GetString("ConfirmarSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar.
        /// </summary>
        internal static string Copiar {
            get {
                return ResourceManager.GetString("Copiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Corte.
        /// </summary>
        internal static string Corte {
            get {
                return ResourceManager.GetString("Corte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string Crear {
            get {
                return ResourceManager.GetString("Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos del cliente.
        /// </summary>
        internal static string DatosCliente {
            get {
                return ResourceManager.GetString("DatosCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar con estos datos la información registrada del cliente..
        /// </summary>
        internal static string DatosClienteActualizar {
            get {
                return ResourceManager.GetString("DatosClienteActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de entrega.
        /// </summary>
        internal static string DatosEntrega {
            get {
                return ResourceManager.GetString("DatosEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconectar.
        /// </summary>
        internal static string Desconectar {
            get {
                return ResourceManager.GetString("Desconectar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descuento.
        /// </summary>
        internal static string Descuento {
            get {
                return ResourceManager.GetString("Descuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descuentos.
        /// </summary>
        internal static string Descuentos {
            get {
                return ResourceManager.GetString("Descuentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle cargo.
        /// </summary>
        internal static string DetalleCargo {
            get {
                return ResourceManager.GetString("DetalleCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle inventario.
        /// </summary>
        internal static string DetalleInventario {
            get {
                return ResourceManager.GetString("DetalleInventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles.
        /// </summary>
        internal static string Detalles {
            get {
                return ResourceManager.GetString("Detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        internal static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos de entrega coinciden con los del cliente..
        /// </summary>
        internal static string DireccionEntregaCoincide {
            get {
                return ResourceManager.GetString("DireccionEntregaCoincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EAN.
        /// </summary>
        internal static string Ean {
            get {
                return ResourceManager.GetString("Ean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elección producto.
        /// </summary>
        internal static string EleccionProducto {
            get {
                return ResourceManager.GetString("EleccionProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Articulo.
        /// </summary>
        internal static string EliminarArticulo {
            get {
                return ResourceManager.GetString("EliminarArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleado.
        /// </summary>
        internal static string Empleado {
            get {
                return ResourceManager.GetString("Empleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        internal static string Empresa {
            get {
                return ResourceManager.GetString("Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En espera.
        /// </summary>
        internal static string EnEspera {
            get {
                return ResourceManager.GetString("EnEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrada cargo.
        /// </summary>
        internal static string EntradaCargo {
            get {
                return ResourceManager.GetString("EntradaCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrada pedido.
        /// </summary>
        internal static string EntradaPedido {
            get {
                return ResourceManager.GetString("EntradaPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviado.
        /// </summary>
        internal static string Enviado {
            get {
                return ResourceManager.GetString("Enviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar POS.
        /// </summary>
        internal static string EnviarPOS {
            get {
                return ResourceManager.GetString("EnviarPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al ejecutar la petición..
        /// </summary>
        internal static string ErrorPeticion {
            get {
                return ResourceManager.GetString("ErrorPeticion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado Actual.
        /// </summary>
        internal static string EstadoActual {
            get {
                return ResourceManager.GetString("EstadoActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha creación.
        /// </summary>
        internal static string FechaCreacion {
            get {
                return ResourceManager.GetString("FechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha última modificación.
        /// </summary>
        internal static string FechaUltimaModificacion {
            get {
                return ResourceManager.GetString("FechaUltimaModificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin.
        /// </summary>
        internal static string Fin {
            get {
                return ResourceManager.GetString("Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar.
        /// </summary>
        internal static string Finalizar {
            get {
                return ResourceManager.GetString("Finalizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foto.
        /// </summary>
        internal static string Foto {
            get {
                return ResourceManager.GetString("Foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gen. Nº.
        /// </summary>
        internal static string GenerarNumero {
            get {
                return ResourceManager.GetString("GenerarNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdArticulo.
        /// </summary>
        internal static string IdArticulo {
            get {
                return ResourceManager.GetString("IdArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id_Cliente.
        /// </summary>
        internal static string IdCliente {
            get {
                return ResourceManager.GetString("IdCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El identificador ya está en uso. Elija otro..
        /// </summary>
        internal static string IdEnUso {
            get {
                return ResourceManager.GetString("IdEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdPedido.
        /// </summary>
        internal static string IdPedido {
            get {
                return ResourceManager.GetString("IdPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir.
        /// </summary>
        internal static string Imprimir {
            get {
                return ResourceManager.GetString("Imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inventario.
        /// </summary>
        internal static string Inventario {
            get {
                return ResourceManager.GetString("Inventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credenciales incorrectas.
        /// </summary>
        internal static string LoginCredencialesIncorrectas {
            get {
                return ResourceManager.GetString("LoginCredencialesIncorrectas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        internal static string Marca {
            get {
                return ResourceManager.GetString("Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a + Tiendas.
        /// </summary>
        internal static string MasTiendas {
            get {
                return ResourceManager.GetString("MasTiendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material.
        /// </summary>
        internal static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modo de visualización.
        /// </summary>
        internal static string ModalidadVisualizacion {
            get {
                return ResourceManager.GetString("ModalidadVisualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo.
        /// </summary>
        internal static string Modelo {
            get {
                return ResourceManager.GetString("Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Móvil.
        /// </summary>
        internal static string Movil {
            get {
                return ResourceManager.GetString("Movil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe ningún cargo con el código introducido..
        /// </summary>
        internal static string NoCargoEntrada {
            get {
                return ResourceManager.GetString("NoCargoEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado información referente al producto solicitado..
        /// </summary>
        internal static string NoInfoProducto {
            get {
                return ResourceManager.GetString("NoInfoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del primer bloque.
        /// </summary>
        internal static string NombrePrimerBloque {
            get {
                return ResourceManager.GetString("NombrePrimerBloque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay ordenes de inventario pendientes..
        /// </summary>
        internal static string NoOrdenesInventario {
            get {
                return ResourceManager.GetString("NoOrdenesInventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe ningún pedido con el código introducido..
        /// </summary>
        internal static string NoPedidoEntrada {
            get {
                return ResourceManager.GetString("NoPedidoEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron productos coincidentes con los datos indicados..
        /// </summary>
        internal static string NoProductosFiltro {
            get {
                return ResourceManager.GetString("NoProductosFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron registros..
        /// </summary>
        internal static string NoResultados {
            get {
                return ResourceManager.GetString("NoResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        internal static string Nuevo {
            get {
                return ResourceManager.GetString("Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo bloque.
        /// </summary>
        internal static string NuevoBloque {
            get {
                return ResourceManager.GetString("NuevoBloque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo cargo.
        /// </summary>
        internal static string NuevoCargo {
            get {
                return ResourceManager.GetString("NuevoCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº cargo.
        /// </summary>
        internal static string NumeroCargo {
            get {
                return ResourceManager.GetString("NumeroCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº pedido.
        /// </summary>
        internal static string NumeroPedido {
            get {
                return ResourceManager.GetString("NumeroPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº Traspaso.
        /// </summary>
        internal static string NumeroTraspaso {
            get {
                return ResourceManager.GetString("NumeroTraspaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        internal static string Observaciones {
            get {
                return ResourceManager.GetString("Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones C/S.
        /// </summary>
        internal static string ObservacionesCS {
            get {
                return ResourceManager.GetString("ObservacionesCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones de tienda.
        /// </summary>
        internal static string ObservacionesTienda {
            get {
                return ResourceManager.GetString("ObservacionesTienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden de inventario.
        /// </summary>
        internal static string OrdenInventario {
            get {
                return ResourceManager.GetString("OrdenInventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Original.
        /// </summary>
        internal static string Original {
            get {
                return ResourceManager.GetString("Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pago Puntos Nine :.
        /// </summary>
        internal static string PagoPuntosNine {
            get {
                return ResourceManager.GetString("PagoPuntosNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        internal static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedido.
        /// </summary>
        internal static string Pedido {
            get {
                return ResourceManager.GetString("Pedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignado.
        /// </summary>
        internal static string PedidoEstadoAsignado {
            get {
                return ResourceManager.GetString("PedidoEstadoAsignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin asignar.
        /// </summary>
        internal static string PedidoEstadoSinAsignar {
            get {
                return ResourceManager.GetString("PedidoEstadoSinAsignar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir un número de pedido para realizar la búsqueda..
        /// </summary>
        internal static string PedidoObligatorio {
            get {
                return ResourceManager.GetString("PedidoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Envíos.
        /// </summary>
        internal static string Pedidos {
            get {
                return ResourceManager.GetString("Pedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entr. Ped..
        /// </summary>
        internal static string PedidosEntrada {
            get {
                return ResourceManager.GetString("PedidosEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Población.
        /// </summary>
        internal static string Poblacion {
            get {
                return ResourceManager.GetString("Poblacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        internal static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto.
        /// </summary>
        internal static string Producto {
            get {
                return ResourceManager.GetString("Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el producto..
        /// </summary>
        internal static string ProductoNoEncontrado {
            get {
                return ResourceManager.GetString("ProductoNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        internal static string Proveedor {
            get {
                return ResourceManager.GetString("Proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia.
        /// </summary>
        internal static string Provincia {
            get {
                return ResourceManager.GetString("Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizado.
        /// </summary>
        internal static string Realizado {
            get {
                return ResourceManager.GetString("Realizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar.
        /// </summary>
        internal static string Realizar {
            get {
                return ResourceManager.GetString("Realizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar pedido.
        /// </summary>
        internal static string RealizarPedido {
            get {
                return ResourceManager.GetString("RealizarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencia.
        /// </summary>
        internal static string Referencia {
            get {
                return ResourceManager.GetString("Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca el identificador de su terminal.
        /// </summary>
        internal static string RegistroTerminalMensaje {
            get {
                return ResourceManager.GetString("RegistroTerminalMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen de Compra.
        /// </summary>
        internal static string ResumenCompra {
            get {
                return ResourceManager.GetString("ResumenCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saldo :.
        /// </summary>
        internal static string SaldoNine {
            get {
                return ResourceManager.GetString("SaldoNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string Salir {
            get {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seccion.
        /// </summary>
        internal static string Seccion {
            get {
                return ResourceManager.GetString("Seccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud Dia.
        /// </summary>
        internal static string SolicitudDia {
            get {
                return ResourceManager.GetString("SolicitudDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes.
        /// </summary>
        internal static string Solicitudes {
            get {
                return ResourceManager.GetString("Solicitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes en estado.
        /// </summary>
        internal static string SolicitudesCabecera {
            get {
                return ResourceManager.GetString("SolicitudesCabecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aparcado.
        /// </summary>
        internal static string SolicitudEstadoAparcado {
            get {
                return ResourceManager.GetString("SolicitudEstadoAparcado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignado.
        /// </summary>
        internal static string SolicitudEstadoAsignado {
            get {
                return ResourceManager.GetString("SolicitudEstadoAsignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelado.
        /// </summary>
        internal static string SolicitudEstadoCancelado {
            get {
                return ResourceManager.GetString("SolicitudEstadoCancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completado.
        /// </summary>
        internal static string SolicitudEstadoCompletado {
            get {
                return ResourceManager.GetString("SolicitudEstadoCompletado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmado.
        /// </summary>
        internal static string SolicitudEstadoConfirmado {
            get {
                return ResourceManager.GetString("SolicitudEstadoConfirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En Piso.
        /// </summary>
        internal static string SolicitudEstadoEnPiso {
            get {
                return ResourceManager.GetString("SolicitudEstadoEnPiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente.
        /// </summary>
        internal static string SolicitudEstadoPendiente {
            get {
                return ResourceManager.GetString("SolicitudEstadoPendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresado.
        /// </summary>
        internal static string SolicitudEstadoRegresado {
            get {
                return ResourceManager.GetString("SolicitudEstadoRegresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitado.
        /// </summary>
        internal static string SolicitudEstadoSolicitado {
            get {
                return ResourceManager.GetString("SolicitudEstadoSolicitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vendido.
        /// </summary>
        internal static string SolicitudEstadoVendido {
            get {
                return ResourceManager.GetString("SolicitudEstadoVendido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información incompleta. Vuelva a ejecutar la solicitud..
        /// </summary>
        internal static string SolicitudFaltanParametros {
            get {
                return ResourceManager.GetString("SolicitudFaltanParametros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud Foránea.
        /// </summary>
        internal static string SolicitudForanea {
            get {
                return ResourceManager.GetString("SolicitudForanea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedido registrado con el nº.
        /// </summary>
        internal static string SolicitudPedidoRegistrado {
            get {
                return ResourceManager.GetString("SolicitudPedidoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud registrada..
        /// </summary>
        internal static string SolicitudRegistrada {
            get {
                return ResourceManager.GetString("SolicitudRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelado.
        /// </summary>
        internal static string SolicituEstadoCancelado {
            get {
                return ResourceManager.GetString("SolicituEstadoCancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock Tienda.
        /// </summary>
        internal static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock.
        /// </summary>
        internal static string StockD {
            get {
                return ResourceManager.GetString("StockD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock Otras.
        /// </summary>
        internal static string StockOtras {
            get {
                return ResourceManager.GetString("StockOtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sub Total.
        /// </summary>
        internal static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtotal.
        /// </summary>
        internal static string Subtotal_Hermes {
            get {
                return ResourceManager.GetString("Subtotal_Hermes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sustitut.
        /// </summary>
        internal static string Sustitutivos {
            get {
                return ResourceManager.GetString("Sustitutivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talla.
        /// </summary>
        internal static string Talla {
            get {
                return ResourceManager.GetString("Talla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono.
        /// </summary>
        internal static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terminal.
        /// </summary>
        internal static string Terminal {
            get {
                return ResourceManager.GetString("Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tienda.
        /// </summary>
        internal static string Tienda {
            get {
                return ResourceManager.GetString("Tienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tienda de destino.
        /// </summary>
        internal static string TiendaDestino {
            get {
                return ResourceManager.GetString("TiendaDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T. Destino.
        /// </summary>
        internal static string TiendaDestinoAbrev {
            get {
                return ResourceManager.GetString("TiendaDestinoAbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tienda de origen.
        /// </summary>
        internal static string TiendaOrigen {
            get {
                return ResourceManager.GetString("TiendaOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T. Origen.
        /// </summary>
        internal static string TiendaOrigenAbrev {
            get {
                return ResourceManager.GetString("TiendaOrigenAbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiendas.
        /// </summary>
        internal static string Tiendas {
            get {
                return ResourceManager.GetString("Tiendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Articulo (Seccion).
        /// </summary>
        internal static string TipoArticulo {
            get {
                return ResourceManager.GetString("TipoArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de inventario.
        /// </summary>
        internal static string TipoInventario {
            get {
                return ResourceManager.GetString("TipoInventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parcial.
        /// </summary>
        internal static string TipoInventarioParcial {
            get {
                return ResourceManager.GetString("TipoInventarioParcial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string TipoInventarioTotal {
            get {
                return ResourceManager.GetString("TipoInventarioTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de vista.
        /// </summary>
        internal static string TipoVista {
            get {
                return ResourceManager.GetString("TipoVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total cargo.
        /// </summary>
        internal static string TotalCargo {
            get {
                return ResourceManager.GetString("TotalCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total entrada.
        /// </summary>
        internal static string TotalEntrada {
            get {
                return ResourceManager.GetString("TotalEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T.E.
        /// </summary>
        internal static string TotalEntrada2 {
            get {
                return ResourceManager.GetString("TotalEntrada2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total pedido.
        /// </summary>
        internal static string TotalPedido {
            get {
                return ResourceManager.GetString("TotalPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T.P.
        /// </summary>
        internal static string TotalPedido2 {
            get {
                return ResourceManager.GetString("TotalPedido2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede realizar un guardado con modo total seleccionado..
        /// </summary>
        internal static string TotalSelec {
            get {
                return ResourceManager.GetString("TotalSelec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total a pagar.
        /// </summary>
        internal static string Total_A_Pagar {
            get {
                return ResourceManager.GetString("Total_A_Pagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ent. Trasp..
        /// </summary>
        internal static string TraspasoEntrada {
            get {
                return ResourceManager.GetString("TraspasoEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Traspasos.
        /// </summary>
        internal static string Traspasos {
            get {
                return ResourceManager.GetString("Traspasos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uds.
        /// </summary>
        internal static string Unidades {
            get {
                return ResourceManager.GetString("Unidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UP.
        /// </summary>
        internal static string UP {
            get {
                return ResourceManager.GetString("UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UT.
        /// </summary>
        internal static string UT {
            get {
                return ResourceManager.GetString("UT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vendedor.
        /// </summary>
        internal static string Vendedor {
            get {
                return ResourceManager.GetString("Vendedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        internal static string Volver {
            get {
                return ResourceManager.GetString("Volver", resourceCulture);
            }
        }
    }
}
