//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLLGestionVenta.ThinkRetailServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Row_Input", Namespace="http://mypiagui.com:1080/")]
    [System.SerializableAttribute()]
    public partial class Row_Input : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PosicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumMaterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TallaField;
        
        private int CantidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Posicion {
            get {
                return this.PosicionField;
            }
            set {
                if ((this.PosicionField.Equals(value) != true)) {
                    this.PosicionField = value;
                    this.RaisePropertyChanged("Posicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NumMaterial {
            get {
                return this.NumMaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.NumMaterialField, value) != true)) {
                    this.NumMaterialField = value;
                    this.RaisePropertyChanged("NumMaterial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Talla {
            get {
                return this.TallaField;
            }
            set {
                if ((object.ReferenceEquals(this.TallaField, value) != true)) {
                    this.TallaField = value;
                    this.RaisePropertyChanged("Talla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Salida", Namespace="http://mypiagui.com:1080/")]
    [System.SerializableAttribute()]
    public partial class Salida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DLLGestionVenta.ThinkRetailServiceReference.Row_Output[] RowsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sts {
            get {
                return this.StsField;
            }
            set {
                if ((object.ReferenceEquals(this.StsField, value) != true)) {
                    this.StsField = value;
                    this.RaisePropertyChanged("Sts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public DLLGestionVenta.ThinkRetailServiceReference.Row_Output[] Rows {
            get {
                return this.RowsField;
            }
            set {
                if ((object.ReferenceEquals(this.RowsField, value) != true)) {
                    this.RowsField = value;
                    this.RaisePropertyChanged("Rows");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Row_Output", Namespace="http://mypiagui.com:1080/")]
    [System.SerializableAttribute()]
    public partial class Row_Output : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PosicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumMaterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TallaField;
        
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DLLGestionVenta.ThinkRetailServiceReference.Mensaje[] MensajesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Posicion {
            get {
                return this.PosicionField;
            }
            set {
                if ((this.PosicionField.Equals(value) != true)) {
                    this.PosicionField = value;
                    this.RaisePropertyChanged("Posicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NumMaterial {
            get {
                return this.NumMaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.NumMaterialField, value) != true)) {
                    this.NumMaterialField = value;
                    this.RaisePropertyChanged("NumMaterial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Talla {
            get {
                return this.TallaField;
            }
            set {
                if ((object.ReferenceEquals(this.TallaField, value) != true)) {
                    this.TallaField = value;
                    this.RaisePropertyChanged("Talla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Sts {
            get {
                return this.StsField;
            }
            set {
                if ((object.ReferenceEquals(this.StsField, value) != true)) {
                    this.StsField = value;
                    this.RaisePropertyChanged("Sts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public DLLGestionVenta.ThinkRetailServiceReference.Mensaje[] Mensajes {
            get {
                return this.MensajesField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajesField, value) != true)) {
                    this.MensajesField = value;
                    this.RaisePropertyChanged("Mensajes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mensaje", Namespace="http://mypiagui.com:1080/")]
    [System.SerializableAttribute()]
    public partial class Mensaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalidaMsg", Namespace="http://mypiagui.com:1080/")]
    [System.SerializableAttribute()]
    public partial class SalidaMsg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DLLGestionVenta.ThinkRetailServiceReference.Mensaje[] MensajesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sts {
            get {
                return this.StsField;
            }
            set {
                if ((object.ReferenceEquals(this.StsField, value) != true)) {
                    this.StsField = value;
                    this.RaisePropertyChanged("Sts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public DLLGestionVenta.ThinkRetailServiceReference.Mensaje[] Mensajes {
            get {
                return this.MensajesField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajesField, value) != true)) {
                    this.MensajesField = value;
                    this.RaisePropertyChanged("Mensajes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mypiagui.com:1080/", ConfigurationName="ThinkRetailServiceReference.wsThinkRetailSoap")]
    public interface wsThinkRetailSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento User del espacio de nombres http://mypiagui.com:1080/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://mypiagui.com:1080/Login", ReplyAction="*")]
        DLLGestionVenta.ThinkRetailServiceReference.LoginResponse Login(DLLGestionVenta.ThinkRetailServiceReference.LoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NoPedido del espacio de nombres http://mypiagui.com:1080/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://mypiagui.com:1080/CreaReservaTR", ReplyAction="*")]
        DLLGestionVenta.ThinkRetailServiceReference.CreaReservaTRResponse CreaReservaTR(DLLGestionVenta.ThinkRetailServiceReference.CreaReservaTRRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NoPedido del espacio de nombres http://mypiagui.com:1080/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://mypiagui.com:1080/ConfirmaReservaTR", ReplyAction="*")]
        DLLGestionVenta.ThinkRetailServiceReference.ConfirmaReservaTRResponse ConfirmaReservaTR(DLLGestionVenta.ThinkRetailServiceReference.ConfirmaReservaTRRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NoPedido del espacio de nombres http://mypiagui.com:1080/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://mypiagui.com:1080/CancelaReservaTR", ReplyAction="*")]
        DLLGestionVenta.ThinkRetailServiceReference.CancelaReservaTRResponse CancelaReservaTR(DLLGestionVenta.ThinkRetailServiceReference.CancelaReservaTRRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://mypiagui.com:1080/", Order=0)]
        public DLLGestionVenta.ThinkRetailServiceReference.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(DLLGestionVenta.ThinkRetailServiceReference.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mypiagui.com:1080/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string User, string Pwd) {
            this.User = User;
            this.Pwd = Pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://mypiagui.com:1080/", Order=0)]
        public DLLGestionVenta.ThinkRetailServiceReference.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(DLLGestionVenta.ThinkRetailServiceReference.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mypiagui.com:1080/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreaReservaTRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreaReservaTR", Namespace="http://mypiagui.com:1080/", Order=0)]
        public DLLGestionVenta.ThinkRetailServiceReference.CreaReservaTRRequestBody Body;
        
        public CreaReservaTRRequest() {
        }
        
        public CreaReservaTRRequest(DLLGestionVenta.ThinkRetailServiceReference.CreaReservaTRRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mypiagui.com:1080/")]
    public partial class CreaReservaTRRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NoPedido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Almacen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NumVendedor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public DLLGestionVenta.ThinkRetailServiceReference.Row_Input[] Posiciones;
        
        public CreaReservaTRRequestBody() {
        }
        
        public CreaReservaTRRequestBody(string NoPedido, string Almacen, string NumVendedor, DLLGestionVenta.ThinkRetailServiceReference.Row_Input[] Posiciones) {
            this.NoPedido = NoPedido;
            this.Almacen = Almacen;
            this.NumVendedor = NumVendedor;
            this.Posiciones = Posiciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreaReservaTRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreaReservaTRResponse", Namespace="http://mypiagui.com:1080/", Order=0)]
        public DLLGestionVenta.ThinkRetailServiceReference.CreaReservaTRResponseBody Body;
        
        public CreaReservaTRResponse() {
        }
        
        public CreaReservaTRResponse(DLLGestionVenta.ThinkRetailServiceReference.CreaReservaTRResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mypiagui.com:1080/")]
    public partial class CreaReservaTRResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DLLGestionVenta.ThinkRetailServiceReference.Salida CreaReservaTRResult;
        
        public CreaReservaTRResponseBody() {
        }
        
        public CreaReservaTRResponseBody(DLLGestionVenta.ThinkRetailServiceReference.Salida CreaReservaTRResult) {
            this.CreaReservaTRResult = CreaReservaTRResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmaReservaTRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmaReservaTR", Namespace="http://mypiagui.com:1080/", Order=0)]
        public DLLGestionVenta.ThinkRetailServiceReference.ConfirmaReservaTRRequestBody Body;
        
        public ConfirmaReservaTRRequest() {
        }
        
        public ConfirmaReservaTRRequest(DLLGestionVenta.ThinkRetailServiceReference.ConfirmaReservaTRRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mypiagui.com:1080/")]
    public partial class ConfirmaReservaTRRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NoPedido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Almacen;
        
        public ConfirmaReservaTRRequestBody() {
        }
        
        public ConfirmaReservaTRRequestBody(string NoPedido, string Almacen) {
            this.NoPedido = NoPedido;
            this.Almacen = Almacen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmaReservaTRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmaReservaTRResponse", Namespace="http://mypiagui.com:1080/", Order=0)]
        public DLLGestionVenta.ThinkRetailServiceReference.ConfirmaReservaTRResponseBody Body;
        
        public ConfirmaReservaTRResponse() {
        }
        
        public ConfirmaReservaTRResponse(DLLGestionVenta.ThinkRetailServiceReference.ConfirmaReservaTRResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mypiagui.com:1080/")]
    public partial class ConfirmaReservaTRResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DLLGestionVenta.ThinkRetailServiceReference.SalidaMsg ConfirmaReservaTRResult;
        
        public ConfirmaReservaTRResponseBody() {
        }
        
        public ConfirmaReservaTRResponseBody(DLLGestionVenta.ThinkRetailServiceReference.SalidaMsg ConfirmaReservaTRResult) {
            this.ConfirmaReservaTRResult = ConfirmaReservaTRResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelaReservaTRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelaReservaTR", Namespace="http://mypiagui.com:1080/", Order=0)]
        public DLLGestionVenta.ThinkRetailServiceReference.CancelaReservaTRRequestBody Body;
        
        public CancelaReservaTRRequest() {
        }
        
        public CancelaReservaTRRequest(DLLGestionVenta.ThinkRetailServiceReference.CancelaReservaTRRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mypiagui.com:1080/")]
    public partial class CancelaReservaTRRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NoPedido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Almacen;
        
        public CancelaReservaTRRequestBody() {
        }
        
        public CancelaReservaTRRequestBody(string NoPedido, string Almacen) {
            this.NoPedido = NoPedido;
            this.Almacen = Almacen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelaReservaTRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelaReservaTRResponse", Namespace="http://mypiagui.com:1080/", Order=0)]
        public DLLGestionVenta.ThinkRetailServiceReference.CancelaReservaTRResponseBody Body;
        
        public CancelaReservaTRResponse() {
        }
        
        public CancelaReservaTRResponse(DLLGestionVenta.ThinkRetailServiceReference.CancelaReservaTRResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mypiagui.com:1080/")]
    public partial class CancelaReservaTRResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DLLGestionVenta.ThinkRetailServiceReference.SalidaMsg CancelaReservaTRResult;
        
        public CancelaReservaTRResponseBody() {
        }
        
        public CancelaReservaTRResponseBody(DLLGestionVenta.ThinkRetailServiceReference.SalidaMsg CancelaReservaTRResult) {
            this.CancelaReservaTRResult = CancelaReservaTRResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsThinkRetailSoapChannel : DLLGestionVenta.ThinkRetailServiceReference.wsThinkRetailSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsThinkRetailSoapClient : System.ServiceModel.ClientBase<DLLGestionVenta.ThinkRetailServiceReference.wsThinkRetailSoap>, DLLGestionVenta.ThinkRetailServiceReference.wsThinkRetailSoap {
        
        public wsThinkRetailSoapClient() {
        }
        
        public wsThinkRetailSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsThinkRetailSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsThinkRetailSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsThinkRetailSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DLLGestionVenta.ThinkRetailServiceReference.LoginResponse DLLGestionVenta.ThinkRetailServiceReference.wsThinkRetailSoap.Login(DLLGestionVenta.ThinkRetailServiceReference.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string User, string Pwd) {
            DLLGestionVenta.ThinkRetailServiceReference.LoginRequest inValue = new DLLGestionVenta.ThinkRetailServiceReference.LoginRequest();
            inValue.Body = new DLLGestionVenta.ThinkRetailServiceReference.LoginRequestBody();
            inValue.Body.User = User;
            inValue.Body.Pwd = Pwd;
            DLLGestionVenta.ThinkRetailServiceReference.LoginResponse retVal = ((DLLGestionVenta.ThinkRetailServiceReference.wsThinkRetailSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DLLGestionVenta.ThinkRetailServiceReference.CreaReservaTRResponse DLLGestionVenta.ThinkRetailServiceReference.wsThinkRetailSoap.CreaReservaTR(DLLGestionVenta.ThinkRetailServiceReference.CreaReservaTRRequest request) {
            return base.Channel.CreaReservaTR(request);
        }
        
        public DLLGestionVenta.ThinkRetailServiceReference.Salida CreaReservaTR(string NoPedido, string Almacen, string NumVendedor, DLLGestionVenta.ThinkRetailServiceReference.Row_Input[] Posiciones) {
            DLLGestionVenta.ThinkRetailServiceReference.CreaReservaTRRequest inValue = new DLLGestionVenta.ThinkRetailServiceReference.CreaReservaTRRequest();
            inValue.Body = new DLLGestionVenta.ThinkRetailServiceReference.CreaReservaTRRequestBody();
            inValue.Body.NoPedido = NoPedido;
            inValue.Body.Almacen = Almacen;
            inValue.Body.NumVendedor = NumVendedor;
            inValue.Body.Posiciones = Posiciones;
            DLLGestionVenta.ThinkRetailServiceReference.CreaReservaTRResponse retVal = ((DLLGestionVenta.ThinkRetailServiceReference.wsThinkRetailSoap)(this)).CreaReservaTR(inValue);
            return retVal.Body.CreaReservaTRResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DLLGestionVenta.ThinkRetailServiceReference.ConfirmaReservaTRResponse DLLGestionVenta.ThinkRetailServiceReference.wsThinkRetailSoap.ConfirmaReservaTR(DLLGestionVenta.ThinkRetailServiceReference.ConfirmaReservaTRRequest request) {
            return base.Channel.ConfirmaReservaTR(request);
        }
        
        public DLLGestionVenta.ThinkRetailServiceReference.SalidaMsg ConfirmaReservaTR(string NoPedido, string Almacen) {
            DLLGestionVenta.ThinkRetailServiceReference.ConfirmaReservaTRRequest inValue = new DLLGestionVenta.ThinkRetailServiceReference.ConfirmaReservaTRRequest();
            inValue.Body = new DLLGestionVenta.ThinkRetailServiceReference.ConfirmaReservaTRRequestBody();
            inValue.Body.NoPedido = NoPedido;
            inValue.Body.Almacen = Almacen;
            DLLGestionVenta.ThinkRetailServiceReference.ConfirmaReservaTRResponse retVal = ((DLLGestionVenta.ThinkRetailServiceReference.wsThinkRetailSoap)(this)).ConfirmaReservaTR(inValue);
            return retVal.Body.ConfirmaReservaTRResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DLLGestionVenta.ThinkRetailServiceReference.CancelaReservaTRResponse DLLGestionVenta.ThinkRetailServiceReference.wsThinkRetailSoap.CancelaReservaTR(DLLGestionVenta.ThinkRetailServiceReference.CancelaReservaTRRequest request) {
            return base.Channel.CancelaReservaTR(request);
        }
        
        public DLLGestionVenta.ThinkRetailServiceReference.SalidaMsg CancelaReservaTR(string NoPedido, string Almacen) {
            DLLGestionVenta.ThinkRetailServiceReference.CancelaReservaTRRequest inValue = new DLLGestionVenta.ThinkRetailServiceReference.CancelaReservaTRRequest();
            inValue.Body = new DLLGestionVenta.ThinkRetailServiceReference.CancelaReservaTRRequestBody();
            inValue.Body.NoPedido = NoPedido;
            inValue.Body.Almacen = Almacen;
            DLLGestionVenta.ThinkRetailServiceReference.CancelaReservaTRResponse retVal = ((DLLGestionVenta.ThinkRetailServiceReference.wsThinkRetailSoap)(this)).CancelaReservaTR(inValue);
            return retVal.Body.CancelaReservaTRResult;
        }
    }
}
