//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34014.
// 
#pragma warning disable 1591

namespace AVE.HermesModaliaWebServiceReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HermesImplSoapBinding", Namespace="http://server.hermes.ecommerce.hermes.com")]
    public partial class HermesImplService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback insertOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateStockOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HermesImplService() {
            this.Url = global::AVE.Properties.Settings.Default.AVE_HermesModaliaWebServiceReference_HermesImplService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event insertOrderCompletedEventHandler insertOrderCompleted;
        
        /// <remarks/>
        public event updateStockCompletedEventHandler updateStockCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://server.hermes.ecommerce.hermes.com", ResponseNamespace="http://server.hermes.ecommerce.hermes.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("insertOrderReturn")]
        public string insertOrder(string login, string password, string idSite, string in0) {
            object[] results = this.Invoke("insertOrder", new object[] {
                        login,
                        password,
                        idSite,
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insertOrderAsync(string login, string password, string idSite, string in0) {
            this.insertOrderAsync(login, password, idSite, in0, null);
        }
        
        /// <remarks/>
        public void insertOrderAsync(string login, string password, string idSite, string in0, object userState) {
            if ((this.insertOrderOperationCompleted == null)) {
                this.insertOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertOrderOperationCompleted);
            }
            this.InvokeAsync("insertOrder", new object[] {
                        login,
                        password,
                        idSite,
                        in0}, this.insertOrderOperationCompleted, userState);
        }
        
        private void OninsertOrderOperationCompleted(object arg) {
            if ((this.insertOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertOrderCompleted(this, new insertOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://server.hermes.ecommerce.hermes.com", ResponseNamespace="http://server.hermes.ecommerce.hermes.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("updateStockReturn")]
        public string updateStock(string login, string password, string idSite, string idTienda, string codigoAlfa, int stock, string tallaOriginalCliente) {
            object[] results = this.Invoke("updateStock", new object[] {
                        login,
                        password,
                        idSite,
                        idTienda,
                        codigoAlfa,
                        stock,
                        tallaOriginalCliente});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateStockAsync(string login, string password, string idSite, string idTienda, string codigoAlfa, int stock, string tallaOriginalCliente) {
            this.updateStockAsync(login, password, idSite, idTienda, codigoAlfa, stock, tallaOriginalCliente, null);
        }
        
        /// <remarks/>
        public void updateStockAsync(string login, string password, string idSite, string idTienda, string codigoAlfa, int stock, string tallaOriginalCliente, object userState) {
            if ((this.updateStockOperationCompleted == null)) {
                this.updateStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateStockOperationCompleted);
            }
            this.InvokeAsync("updateStock", new object[] {
                        login,
                        password,
                        idSite,
                        idTienda,
                        codigoAlfa,
                        stock,
                        tallaOriginalCliente}, this.updateStockOperationCompleted, userState);
        }
        
        private void OnupdateStockOperationCompleted(object arg) {
            if ((this.updateStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateStockCompleted(this, new updateStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void insertOrderCompletedEventHandler(object sender, insertOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void updateStockCompletedEventHandler(object sender, updateStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591